Sprint 3/step 1
comradeskolopendra/react-burger pull request #4
Opened 2023-10-06 10:43 UTC by comradeskolopendra

настроил роутинг. создал protected-route.
добавил запросы - изменение пароля, логин, регистрация, выход
создал подстраницы логина. компонент изменяемого инпута.
защитил /reset-password от перехода с других страниц.
информация об ингредиенте открывается как на отдельной странице, так и в модалке

2023-10-06 15:07 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Настроена защита роутов
- Реализован механизм обновления токена
- Настроены все редиректы
- Отличная работа с формами

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Авторизация сбрасывается при перезагрузке страницы
- На странице профиля невозможно поменять значение в инпуте пароля и это значение не попадает в payload запроса
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- Для `logout` использовать функцию `requestWithRefresh` не нужно, так как нет смысла обновлять токен, чтобы тут же его сделать неактуальным.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-06 15:07 UTC, andryxxa93 commented on src/components/app/app.jsx
> +                    path="/login"
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-10-06 18:53 UTC, comradeskolopendra commented on src/components/app/app.jsx
> +                    path="/login"
@andryxxa93 здравствуйте. я не знаю, где ещё могу вам написать, поэтому сделаю это здесь:
1. а откуда берется пароль? мне ни на один эндпоинт это не приходит. 
2. как должна происходить смена пароля? через PATCH на эндпоинте /user? Если да, то информацию о пользователе и о пароле мне хранить в разных местах?

2023-10-10 10:49 UTC, andryxxa93 commented on src/components/app/app.jsx
> +                    path="/login"
Здравствуйте! Пароль не приходит и это правильно, потому что обеспечивает безопасность. Вы правильно организовали смену пароля. Не очень понял вопрос насчет пароля, его нигде хранить не нужно.

Если что вы можете написать мне в пачке или через своего куратора

2023-10-10 10:49 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-11 03:29 UTC, merged